### ISSUE TITLE
Inject rather than Map for more idiomatic Ruby

### ISSUE THREAD

**Issue by Yorkshireman** [Yorkshireman/promotest#1]
Here: https://github.com/Yorkshireman/promotest/blob/master/lib/checkout.rb#L19

**Comment by Yorkshireman** [comment]
I agree with using #inject here - it's more concise. I refactored using #inject and committed the code. You can view that [here](https://github.com/Yorkshireman/promotest/blob/a33e754e1ee1e44017a27608aff650022f4d7943/lib/checkout.rb) (line 18).

**Comment by dwfait** [comment]
Nice.

I'm not usually on board with the 'less lines of code = better code' dogma, but the essence of it is that if you can express intent with less code / parts of the language getting in the way, the more your code is easily read and understood, therefore easier to change or extend.

More important than lines of code, in my opinion, is maintaining an abstraction level. For example, now in your `total` method, you have a line of ruby code that reads quite 'technically', and then two lines you could read as 'english' and not have to think about what they do. To make the method even easier to read, I would hide away the implementation details somewhere, and let the method read something like this:

```
  def total
    total = total_before_promotions
    total = promotional_rules.apply_promotions(total, basket)
    apply_currency_formatting(total)
  end

private
  def total_before_promotions
    basket.inject(0){ |sum_total, product_code| sum_total + ProductRange.items[product_code][:price] }
  end
```

Now the intent is clear to what we're doing, but the implementation details aren't important. We could go further and question why we're storing the variable at all now that we have an easy way to access it:

```Ruby
  def total
    total = promotional_rules.apply_promotions(total_before_promotions, basket)
    apply_currency_formatting(total)
  end

private
  def total_before_promotions
    basket.inject(0){ |sum_total, product_code| sum_total + ProductRange.items[product_code][:price] }
  end
```

this now reduces the `total` method's responsibilities to applying promotions to a total, and formatting the currency. Could always go further, but I'll leave that as an exercise to the reader :)

**Comment by Yorkshireman** [comment]
I like this a lot because I'm _obsessed_ with refactoring things out into other methods to make methods more readable, but this is first time I've seen anyone else apply the same technique to such an extent. Because I haven't seen anyone else do it before, I've always held back on it! This gives me permission to go to town on it. When is too much too much?

**Comment by Yorkshireman** [comment]
PS about the 'less lines of code = better code', I couldn't agree more - it's about balance; you only have to look at the 'best' solutions on Codewars to see fantastic examples of extremely concise but unreadable lines of code. Ironically these solutions always get the most points!

**Comment by dwfait** [comment]
I recently watched a fantastic talk on refactoring by Ben Orenstein, with a nugget paraphrased as "Your public API (public methods) should always read like a story". The sentiment is also in many software engineering books, such as Code Complete.

The key tenet of software is always "easy to change". To be easy to change, it must be easily understood. If you can read your code like a sentence, and it makes sense to someone who's fairly familiar with the domain, then it does its job. 

```Ruby
    total = promotional_rules.apply_promotions(total_before_promotions, basket)
    apply_currency_formatting(total)
```

That's pretty easy to understand what's going on without really thinking too hard. 

```Ruby
  basket.inject(0){ |sum_total, product_code| sum_total + ProductRange.items[product_code][:price] }
```
That line, is quite dense, however. There's a lot there going on, and we have to hold a lot of context in our heads to understand what this line _represents_, which once it's been written, is all we really care about (with a decent test suite, you can assume it works). This is now an implementation detail that's squirrelled away in a private method that has a good name signalling us its intent. If I did need to come and change how the total was calculated, I'd know where to look, and I could make the change with it being pretty clear what this private method was supposed to return. 

If all the implementation details of my code are hidden away, I'm using the correct abstraction levels, my code has single responsibilities and I'm confident that the code is easy to change, I'll stop. 

There is of course going too far, and I've seen plenty of code where things have been pulled out and extracted so much, that you had to follow about 20 layers of indirection to actually find the code that _did stuff_. This is not good code that is easy to understand or change. 

There are unfortunately no real hard guidelines to avoid either extreme, it will mostly come from experience, and from seeing a lot of bad code (of which you will see plenty, don't worry :P)


> Ironically these solutions always get the most points!
Yup. Most hobbyists do it for fun - it's a way of showing off with 'clever code'. It's popular because clever code can be fun; there's always someone trying to build a better mousetrap. Commercially, clever code is seen as more an anti-pattern, and frowned upon. "Debugging is harder than writing code. Therefore, if you write the smartest code you can, by definition, you are not smart enough to debug it."

**Comment by Yorkshireman** [comment]
Lol. Thanks for all that, very informative. I do have a question: when squirreling away implementation methods into private methods, do you abandon testing those methods directly? Quite often when I'm writing code, I'll finish a feature with imperfect code that works, then refactor. And when I refactor, I often want to refactor things out into private methods, but then my test can't access it, so I sometimes leave it as public. This has happened several times while I was writing this actually.

I don't know how to test private methods, but I think it's possible but difficult? Or do you leave those private methods untested directly, and just be content that they are being tested indirectly?

**Comment by dwfait** [comment]
I never test private methods. I see them as 'helpers' of my public API. If their behaviour isn't observable and testable throughout my API, then they're not really doing much and their existence needs to be re-evaluated. 

Think about it this way: this new private method, it's _behaviour_ is still tested from your test suite, because the `total` method is still tested, right? What does it matter where that behaviour lives? Our behaviour is still correct, and that's what matters. 

Testing private methods is a symptom of over-fitting a test suite, and makes your test suite more brittle. If I wanted to extract out the behaviour to a class, then my tests would break, even though the behaviour would stay the same.

If I were to extract it out to a class, then I would write tests for it - because then it would have a public API which would need guarantees around it.

**Comment by dwfait** [comment]
Btw in ruby, to test private methods if you really, really wanted to, you could use `send(:method_name)` on an object. It by-passes access modifier checks.

**Comment by Yorkshireman** [comment]
Come to think of it, this problem would only occur if I was moving a whole method from public to private. If I'm just moving some lines out into a new method that is private, that wouldn't affect the existing tests.
